### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by dloosli** [PeterLemon/RaspberryPi#15]
Hello Peter

Currently, I am writing a research study at the University of Applied Science HSR (Switzerland). I would like to present your CPU HelloWorld code for the RPI3 in this study and therefore wanted to ask you under which license you published your code.

Thanks for your reply and your efforts!

Best regards, David

**Comment by PeterLemon** [comment]
Hi David,

I have not licensed my code under any particular license.

You can do what you want with my GitHub repository source code.
I hope it helps you out, good luck with your research study =D

**Comment by dloosli** [comment]
Hi Peter

Thanks a lot for your quick reply!! Great that I can use your code for my research study -  it really helped me a lot to understand the basics!!

Thanks again for your great work!!

David

**Comment by PeterLemon** [comment]
Hi David,

No problem, I hope you have fun with your research study =D
Thanks for the kind words.
