### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by OllieLollie1** [PeterLemon/RaspberryPi#17]
As you can see by the title this isn't an issue about your code at all. Recently I tried to rewrite your 14 bit 44100Hz Mono CPU code in C however I have run into an error somewhere because it doesn't work. I have been able to rule out unaligned memory access as the culprit however I'm sure there is still much I don't know I have posted my question to https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=212930&sid=aeafdbf5f08d4d0563e61392c6cac157. Thank you if you can help!

**Comment by PeterLemon** [comment]
Hi OllieLollie1
Sorry for the late reply, hmm it could be a cache problem, I do not use C on R-Pi myself, so could be lots of things I reckon...
I hope you are able to find a solution to your problem =D
