### ISSUE TITLE
14bit Audio

### ISSUE THREAD

**Issue by OllieLollie1** [PeterLemon/RaspberryPi#18]
When I try to play audio through the audio output on the pi the quality is much worse than other devices. I'm wondering is 14bit too low and is it running out of precision? If there are any other ways to make the audio sound clearer please state them also.

**Comment by PeterLemon** [comment]
Hi OllieLollie1,

Sorry for the late reply, I made the 14-bit mono PWM test to show the max throughput of the PWM on R-Pi, it is not very good quality, but I recommend 12-bit stereo PWM output if using the analogue audio output on R-Pi for best quality/stable output on there, you can only do higher audio bit-rates than 14-bit on R-Pi using digital HDMI output. I hope this helps =D
