### ISSUE TITLE
Stereo Audio not stereo

### ISSUE THREAD

**Issue by OllieLollie1** [PeterLemon/RaspberryPi#19]
In your 12bit 44100Hz stereo cpu demo the audio doesn't actually come out in both sides of the headphones. The headphones are perfectly functional in other devices it seems like this code doesn't actually give stereo output. Is there a way to make the code stereo?

**Comment by PeterLemon** [comment]
Hi OllieLollie1,

My demos are stereo, I think you are using a R-pi newer than version 1, these newer R-pi's use a 3 prong jack for stereo audio & composite video, I noticed sometimes my stereo headphones when pushed all the way in have mono output on my Stereo Audio demos, you will need to either buy a 3 prong input jack, or push your stereo headphones not all the way into the jack to hear Stereo Sound, I hope this helps.

**Comment by OllieLollie1** [comment]
Yes I have a Pi 3B. My headphones have three black rings. Wouldn't that indicate that it should be stereo sound even with the composite video? I tried putting them in part way however isn't that just duplicating the mono channel across two outputs?

**Comment by OllieLollie1** [comment]
Thanks I will try that.

________________________________
