### ISSUE TITLE
Screen resolution of framebuffer suboptimal

### ISSUE THREAD

**Issue by mrvn** [PeterLemon/RaspberryPi#5]
The resolution of the framebuffer seem to be hardcoded in various demos causing the (at least here) picture to be scaled up with tons of scaling artefacts. Makes text output rather hard to read and images look ugly.

You can query the native screen resolution and then request a framebuffer of the ideal size. This would greatly improve the visual quality of the demos and be educational too.

PS: great collection of demos

**Comment by PeterLemon** [comment]
Thanks mrvn, I chose 640x480 as the native resolution in my demos, as this works on NTSC CRT, PAL CRT, & HDMI T.V's, I do not have a detection routine to make my demos simpler.
