### ISSUE TITLE
Can't boot on RPI3

### ISSUE THREAD

**Issue by nekorobov** [PeterLemon/RaspberryPi#9]
Hi, I have RPI2 and booted bare metal examples there, but now I'm trying to boot on RPI3 in any(x64, x86) mode. I have formated sd card with https://github.com/raspberrypi/firmware/tree/master/boot files and your kernel8.img HelloWorld example. There are only one blink of green light on RPI and red light other time. What's wrong with me and my RPI?

**Comment by PeterLemon** [comment]
Hi nekorobov,
I just tried latest "bootcode.bin" - kernel: Added Overlay for Microchip MCP23017 I2C gpio expander
& "start.elf" - kernel: Bump to 4.4.16
from the URL you linked with my https://github.com/PeterLemon/RaspberryPi/blob/master/boot/config.txt file
& my Julia fractal demo here:
https://github.com/PeterLemon/RaspberryPi/blob/master/VFP/Fractal/Julia/Double/kernel8.img
& it booted correctly & ran on my R-Pi3...

Could you please try these files, on your SD card, & see if it works...
If it does not work please try another SD card just to make sure it is not a problem with the SD card you are currently using.

Let me know how you get on, I hope it now works for you =D
